// Proxies /og/<photoId> to the OG image PNG stored in the R2 public bucket.
// The PNGs are generated by Afilmory's ogImagePlugin (see builder.config.ts).
// Kept in sync with builder.config.ts -> ogImagePlugin.vendor.storageURL.
const OG_BASE = 'https://pub-f5d6344f27c64d548d5ed2c2d6ebb492.r2.dev'

export const onRequest: PagesFunction = async (context) => {
  const raw = context.params.photoId
  const photoId = Array.isArray(raw) ? raw[0] : raw
  if (!photoId) return new Response('photoId missing', { status: 400 })

  const target = `${OG_BASE}/.afilmory/og-images/${encodeURIComponent(photoId)}.png`
  const upstream = await fetch(target, { cf: { cacheTtl: 3600 } as any })
  if (!upstream.ok) {
    return new Response(`OG image not found for "${photoId}"`, { status: 404 })
  }

  const headers = new Headers()
  const ct = upstream.headers.get('content-type')
  if (ct) headers.set('content-type', ct)
  headers.set('cache-control', 'public, max-age=3600')
  return new Response(upstream.body, { status: 200, headers })
}
